{"hierarchy":{"paths":[["doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"modules":[{"name":"SotoCore"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"internalFailure","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:8SotoCore14AWSServerErrorV","text":"AWSServerError","kind":"typeIdentifier"}],"title":"internalFailure","role":"symbol","symbolKind":"property","externalID":"s:8SotoCore14AWSServerErrorV15internalFailureACvpZ","roleHeading":"Type Property"},"variants":[{"paths":["\/documentation\/sotocore\/awsservererror\/internalfailure"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError\/internalFailure"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalFailure"},{"text":": ","kind":"text"},{"text":"AWSServerError","kind":"typeIdentifier","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError","preciseIdentifier":"s:8SotoCore14AWSServerErrorV"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://codes.soto.soto-core/documentation/SotoCore/AWSServerError/internalFailure":{"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError\/internalFailure","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"internalFailure"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:8SotoCore14AWSServerErrorV","kind":"typeIdentifier","text":"AWSServerError"}],"kind":"symbol","title":"internalFailure","url":"\/documentation\/sotocore\/awsservererror\/internalfailure","role":"symbol","type":"topic"},"doc://codes.soto.soto-core/documentation/SotoCore":{"type":"topic","role":"collection","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","kind":"symbol","abstract":[{"text":"The core framework for Soto, a Swift SDK for AWS","type":"text"}],"url":"\/documentation\/sotocore","title":"SotoCore"},"doc://codes.soto.soto-core/documentation/SotoCore/AWSServerError":{"type":"topic","title":"AWSServerError","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWSServerError"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError","url":"\/documentation\/sotocore\/awsservererror","navigatorTitle":[{"kind":"identifier","text":"AWSServerError"}]}}}